version: '3.9'

services: 
  pg:
    image: postgres
    container_name: pg
    restart: always
    env_file: .env
    ports: 
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot

  bot:
    container_name: bot
    depends_on: 
      - pg
    build: 
      context: .
    restart: always
    env_file: .env
    command: node src/bot
    networks:
      - bot

volumes: 
  pgdata:

networks:
  bot:
    driver: bridge 